# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BattleMatShowCfg.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x42\x61ttleMatShowCfg.proto\x12\x10\x42\x61ttleMatShowCfg\"/\n\x08\x43\x66gTable\x12#\n\x04\x44\x61ta\x18\x01 \x03(\x0b\x32\x15.BattleMatShowCfg.Cfg\"\x9a\x02\n\x03\x43\x66g\x12\n\n\x02Id\x18\x01 \x01(\x05\x12\x13\n\x0bIsContinued\x18\x02 \x01(\x08\x12\x15\n\rDurationFrame\x18\x03 \x01(\x05\x12\x11\n\tLoopCount\x18\x04 \x01(\x05\x12\x12\n\nResetAlpha\x18\x05 \x01(\x08\x12\x12\n\nWholeAlpha\x18\x06 \x01(\x05\x12\x15\n\rOutlineEnable\x18\x07 \x01(\x08\x12\x14\n\x0cOutlineColor\x18\x08 \x01(\t\x12\x1d\n\x15OutlineColorIntensity\x18\t \x01(\x05\x12\x15\n\rOutlineDetail\x18\n \x01(\x05\x12\x14\n\x0cOutlineWider\x18\x0b \x01(\x05\x12\x14\n\x0cOutlineScale\x18\x0c \x01(\x05\x12\x11\n\tMainColor\x18\r \x01(\tb\x06proto3')



_CFGTABLE = DESCRIPTOR.message_types_by_name['CfgTable']
_CFG = DESCRIPTOR.message_types_by_name['Cfg']
CfgTable = _reflection.GeneratedProtocolMessageType('CfgTable', (_message.Message,), {
  'DESCRIPTOR' : _CFGTABLE,
  '__module__' : 'BattleMatShowCfg_pb2'
  # @@protoc_insertion_point(class_scope:BattleMatShowCfg.CfgTable)
  })
_sym_db.RegisterMessage(CfgTable)

Cfg = _reflection.GeneratedProtocolMessageType('Cfg', (_message.Message,), {
  'DESCRIPTOR' : _CFG,
  '__module__' : 'BattleMatShowCfg_pb2'
  # @@protoc_insertion_point(class_scope:BattleMatShowCfg.Cfg)
  })
_sym_db.RegisterMessage(Cfg)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CFGTABLE._serialized_start=44
  _CFGTABLE._serialized_end=91
  _CFG._serialized_start=94
  _CFG._serialized_end=376
# @@protoc_insertion_point(module_scope)
