# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BattleUltSpecTimelineCfg.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x42\x61ttleUltSpecTimelineCfg.proto\x12\x18\x42\x61ttleUltSpecTimelineCfg\"7\n\x08\x43\x66gTable\x12+\n\x04\x44\x61ta\x18\x01 \x03(\x0b\x32\x1d.BattleUltSpecTimelineCfg.Cfg\"\xe4\x01\n\x03\x43\x66g\x12\x0f\n\x07SkillId\x18\x01 \x01(\x05\x12\x14\n\x0cPlayablePath\x18\x02 \x01(\t\x12\x1a\n\x12\x43\x61meraPositionType\x18\x03 \x01(\x05\x12\x1a\n\x12\x43\x61meraPositionBone\x18\x04 \x01(\x05\x12\x18\n\x10\x43\x61meraFollowType\x18\x05 \x01(\x05\x12\x18\n\x10\x43\x61meraFollowBone\x18\x06 \x01(\x05\x12\x18\n\x10\x43\x61meraLookatType\x18\x07 \x01(\x05\x12\x18\n\x10\x43\x61meraLookatBone\x18\x08 \x01(\x05\x12\x16\n\x0e\x43\x61meraHideType\x18\t \x01(\x05\x62\x06proto3')



_CFGTABLE = DESCRIPTOR.message_types_by_name['CfgTable']
_CFG = DESCRIPTOR.message_types_by_name['Cfg']
CfgTable = _reflection.GeneratedProtocolMessageType('CfgTable', (_message.Message,), {
  'DESCRIPTOR' : _CFGTABLE,
  '__module__' : 'BattleUltSpecTimelineCfg_pb2'
  # @@protoc_insertion_point(class_scope:BattleUltSpecTimelineCfg.CfgTable)
  })
_sym_db.RegisterMessage(CfgTable)

Cfg = _reflection.GeneratedProtocolMessageType('Cfg', (_message.Message,), {
  'DESCRIPTOR' : _CFG,
  '__module__' : 'BattleUltSpecTimelineCfg_pb2'
  # @@protoc_insertion_point(class_scope:BattleUltSpecTimelineCfg.Cfg)
  })
_sym_db.RegisterMessage(Cfg)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CFGTABLE._serialized_start=60
  _CFGTABLE._serialized_end=115
  _CFG._serialized_start=118
  _CFG._serialized_end=346
# @@protoc_insertion_point(module_scope)
