# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BreakConfigCfg.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x42reakConfigCfg.proto\x12\x0e\x42reakConfigCfg\"-\n\x08\x43\x66gTable\x12!\n\x04\x44\x61ta\x18\x01 \x03(\x0b\x32\x13.BreakConfigCfg.Cfg\"\x88\x02\n\x03\x43\x66g\x12\x0f\n\x07\x42reakId\x18\x01 \x01(\x05\x12\x10\n\x08\x42reakNum\x18\x02 \x01(\x05\x12\x14\n\x0c\x44\x61mageReduce\x18\x03 \x01(\x05\x12\x16\n\x0e\x44\x61mageIncrease\x18\x04 \x01(\x05\x12\x11\n\tBreakTime\x18\x05 \x01(\x05\x12\x14\n\x0cIntervalTime\x18\x06 \x01(\x05\x12\x0f\n\x07\x46\x65\x61ture\x18\x07 \x03(\x05\x12\x13\n\x0bIncreaseNum\x18\x08 \x03(\x05\x12\x13\n\x0b\x42reakEffect\x18\t \x01(\x05\x12\x0f\n\x07\x44\x65sIcon\x18\n \x01(\t\x12\x13\n\x0b\x44\x65scription\x18\x0b \x01(\t\x12\x15\n\rDescriptionLv\x18\x0c \x01(\t\x12\x0f\n\x07\x44\x65sName\x18\r \x01(\tb\x06proto3')



_CFGTABLE = DESCRIPTOR.message_types_by_name['CfgTable']
_CFG = DESCRIPTOR.message_types_by_name['Cfg']
CfgTable = _reflection.GeneratedProtocolMessageType('CfgTable', (_message.Message,), {
  'DESCRIPTOR' : _CFGTABLE,
  '__module__' : 'BreakConfigCfg_pb2'
  # @@protoc_insertion_point(class_scope:BreakConfigCfg.CfgTable)
  })
_sym_db.RegisterMessage(CfgTable)

Cfg = _reflection.GeneratedProtocolMessageType('Cfg', (_message.Message,), {
  'DESCRIPTOR' : _CFG,
  '__module__' : 'BreakConfigCfg_pb2'
  # @@protoc_insertion_point(class_scope:BreakConfigCfg.Cfg)
  })
_sym_db.RegisterMessage(Cfg)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CFGTABLE._serialized_start=40
  _CFGTABLE._serialized_end=85
  _CFG._serialized_start=88
  _CFG._serialized_end=352
# @@protoc_insertion_point(module_scope)
