# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DormFightItemCfg.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x44ormFightItemCfg.proto\x12\x10\x44ormFightItemCfg\"/\n\x08\x43\x66gTable\x12#\n\x04\x44\x61ta\x18\x01 \x03(\x0b\x32\x15.DormFightItemCfg.Cfg\"\x92\x01\n\x03\x43\x66g\x12\x0e\n\x06ItemId\x18\x01 \x01(\x05\x12\x0c\n\x04Type\x18\x02 \x01(\x05\x12\x0c\n\x04Name\x18\x03 \x01(\t\x12\x12\n\nPrefabPath\x18\x04 \x01(\t\x12\x10\n\x08PickSeId\x18\x05 \x03(\x05\x12\x19\n\x11\x43ollidingItemSeId\x18\x06 \x03(\x05\x12\x1e\n\x16\x43ollidingCharacterSeId\x18\x07 \x03(\x05\x62\x06proto3')



_CFGTABLE = DESCRIPTOR.message_types_by_name['CfgTable']
_CFG = DESCRIPTOR.message_types_by_name['Cfg']
CfgTable = _reflection.GeneratedProtocolMessageType('CfgTable', (_message.Message,), {
  'DESCRIPTOR' : _CFGTABLE,
  '__module__' : 'DormFightItemCfg_pb2'
  # @@protoc_insertion_point(class_scope:DormFightItemCfg.CfgTable)
  })
_sym_db.RegisterMessage(CfgTable)

Cfg = _reflection.GeneratedProtocolMessageType('Cfg', (_message.Message,), {
  'DESCRIPTOR' : _CFG,
  '__module__' : 'DormFightItemCfg_pb2'
  # @@protoc_insertion_point(class_scope:DormFightItemCfg.Cfg)
  })
_sym_db.RegisterMessage(Cfg)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CFGTABLE._serialized_start=44
  _CFGTABLE._serialized_end=91
  _CFG._serialized_start=94
  _CFG._serialized_end=240
# @@protoc_insertion_point(module_scope)
