# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BattleSkillCfg.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x42\x61ttleSkillCfg.proto\x12\x0e\x42\x61ttleSkillCfg\"-\n\x08\x43\x66gTable\x12!\n\x04\x44\x61ta\x18\x01 \x03(\x0b\x32\x13.BattleSkillCfg.Cfg\"\xc5\x05\n\x03\x43\x66g\x12\n\n\x02Id\x18\x01 \x01(\x05\x12\x0c\n\x04Name\x18\x02 \x01(\t\x12\x14\n\x0c\x41udioSkillId\x18\x03 \x01(\x05\x12\x10\n\x08\x44\x65scribe\x18\x04 \x01(\t\x12\x12\n\nDescribeLv\x18\x05 \x01(\t\x12\x10\n\x08HurtType\x18\x06 \x01(\x05\x12\x0f\n\x07\x46ormula\x18\x07 \x03(\x05\x12\x12\n\nFormulaArg\x18\x08 \x03(\x05\x12\x13\n\x0b\x46ormulaArg2\x18\t \x03(\x05\x12\x13\n\x0b\x46ormulaArg3\x18\n \x03(\x05\x12\x0c\n\x04Icon\x18\x0b \x01(\t\x12\x11\n\tTypeColor\x18\x0c \x01(\x05\x12\x12\n\nSkillMovie\x18\r \x01(\t\x12\x10\n\x08Priority\x18\x0e \x01(\x05\x12\x10\n\x08SkillTag\x18\x0f \x01(\x05\x12\x15\n\rIsBreakComAtk\x18\x10 \x01(\x08\x12\x0e\n\x06\x43\x64Time\x18\x11 \x01(\x05\x12\x16\n\x0eTotalCdFormula\x18\x12 \x01(\x05\x12\x12\n\nTotalCdArg\x18\x13 \x01(\x05\x12\x13\n\x0bStartCdRank\x18\x14 \x03(\x05\x12\x16\n\x0eStartCdRankNum\x18\x15 \x03(\x05\x12\x10\n\x08UseLimit\x18\x16 \x01(\x05\x12\x11\n\tLuaScript\x18\x17 \x01(\t\x12\x14\n\x0cMoveTargetAi\x18\x18 \x01(\x05\x12\x1c\n\x14\x43ontainExtraMovesort\x18\x19 \x01(\x08\x12\x12\n\nSkillRange\x18\x1a \x01(\x05\x12\x14\n\x0cPlayerMpCost\x18\x1b \x01(\x05\x12\x16\n\x0eRangeDeviation\x18\x1c \x01(\x05\x12\x0c\n\x04Turn\x18\x1d \x01(\x08\x12\x0f\n\x07Quality\x18\x1e \x01(\x05\x12\x12\n\nManualMode\x18\x1f \x01(\x08\x12\x12\n\nFuncHeroid\x18  \x01(\x05\x12\x11\n\tGridSkill\x18! \x01(\x05\x12\x12\n\nGridEffect\x18\" \x01(\t\x12\x10\n\x08\x42reakNum\x18# \x01(\x05\x12\x13\n\x0bSkillIsShow\x18$ \x01(\x08\x62\x06proto3')



_CFGTABLE = DESCRIPTOR.message_types_by_name['CfgTable']
_CFG = DESCRIPTOR.message_types_by_name['Cfg']
CfgTable = _reflection.GeneratedProtocolMessageType('CfgTable', (_message.Message,), {
  'DESCRIPTOR' : _CFGTABLE,
  '__module__' : 'BattleSkillCfg_pb2'
  # @@protoc_insertion_point(class_scope:BattleSkillCfg.CfgTable)
  })
_sym_db.RegisterMessage(CfgTable)

Cfg = _reflection.GeneratedProtocolMessageType('Cfg', (_message.Message,), {
  'DESCRIPTOR' : _CFG,
  '__module__' : 'BattleSkillCfg_pb2'
  # @@protoc_insertion_point(class_scope:BattleSkillCfg.Cfg)
  })
_sym_db.RegisterMessage(Cfg)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CFGTABLE._serialized_start=40
  _CFGTABLE._serialized_end=85
  _CFG._serialized_start=88
  _CFG._serialized_end=797
# @@protoc_insertion_point(module_scope)
