# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BattleTargetSelectCfg.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x42\x61ttleTargetSelectCfg.proto\x12\x15\x42\x61ttleTargetSelectCfg\"4\n\x08\x43\x66gTable\x12(\n\x04\x44\x61ta\x18\x01 \x03(\x0b\x32\x1a.BattleTargetSelectCfg.Cfg\"\x86\x02\n\x03\x43\x66g\x12\n\n\x02Id\x18\x01 \x01(\x05\x12\x16\n\x0eTargetTypeCode\x18\x02 \x01(\x05\x12\x11\n\tSelectAll\x18\x03 \x01(\x08\x12\x15\n\rSelectFormula\x18\x04 \x01(\t\x12\x13\n\x0bSelectOrder\x18\x05 \x01(\x05\x12\x17\n\x0fNeutralSeparate\x18\x06 \x01(\x05\x12\x14\n\x0cOrderFormula\x18\x07 \x01(\t\x12\x15\n\rIsAscendOrder\x18\x08 \x01(\x08\x12\x14\n\x0cTargetNumber\x18\t \x01(\x05\x12\x11\n\tExtraType\x18\n \x01(\x05\x12\x1b\n\x13\x45xtraTargetTypeCode\x18\x0b \x01(\x05\x12\x10\n\x08MoveCode\x18\x0c \x01(\x05\x62\x06proto3')



_CFGTABLE = DESCRIPTOR.message_types_by_name['CfgTable']
_CFG = DESCRIPTOR.message_types_by_name['Cfg']
CfgTable = _reflection.GeneratedProtocolMessageType('CfgTable', (_message.Message,), {
  'DESCRIPTOR' : _CFGTABLE,
  '__module__' : 'BattleTargetSelectCfg_pb2'
  # @@protoc_insertion_point(class_scope:BattleTargetSelectCfg.CfgTable)
  })
_sym_db.RegisterMessage(CfgTable)

Cfg = _reflection.GeneratedProtocolMessageType('Cfg', (_message.Message,), {
  'DESCRIPTOR' : _CFG,
  '__module__' : 'BattleTargetSelectCfg_pb2'
  # @@protoc_insertion_point(class_scope:BattleTargetSelectCfg.Cfg)
  })
_sym_db.RegisterMessage(Cfg)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CFGTABLE._serialized_start=54
  _CFGTABLE._serialized_end=106
  _CFG._serialized_start=109
  _CFG._serialized_end=371
# @@protoc_insertion_point(module_scope)
