# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: HeroPvpFightCfg.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15HeroPvpFightCfg.proto\x12\x0fHeroPvpFightCfg\".\n\x08\x43\x66gTable\x12\"\n\x04\x44\x61ta\x18\x01 \x03(\x0b\x32\x14.HeroPvpFightCfg.Cfg\"\xa0\x02\n\x03\x43\x66g\x12\x12\n\nHeroTypeId\x18\x01 \x01(\x05\x12\x13\n\x0bHeroModelId\x18\x02 \x01(\x05\x12\n\n\x02Hp\x18\x03 \x01(\x05\x12\r\n\x05MaxHp\x18\x04 \x01(\x05\x12\n\n\x02\x45p\x18\x05 \x01(\x05\x12\r\n\x05MaxEp\x18\x06 \x01(\x05\x12\x1a\n\x12\x45pRecoverPerSecond\x18\x07 \x01(\x05\x12\x1a\n\x12\x45pRecoverCdMileSec\x18\x08 \x01(\x05\x12\x13\n\x0b\x41ttackPower\x18\t \x01(\x05\x12\x18\n\x10\x45pReduceByAttack\x18\n \x01(\x05\x12\x19\n\x11WalkSpeedMultiple\x18\x0b \x01(\x05\x12\x18\n\x10RunSpeedMultiple\x18\x0c \x01(\x05\x12\x1e\n\x16\x45pReduceByRunPerSecond\x18\r \x01(\x05\x62\x06proto3')



_CFGTABLE = DESCRIPTOR.message_types_by_name['CfgTable']
_CFG = DESCRIPTOR.message_types_by_name['Cfg']
CfgTable = _reflection.GeneratedProtocolMessageType('CfgTable', (_message.Message,), {
  'DESCRIPTOR' : _CFGTABLE,
  '__module__' : 'HeroPvpFightCfg_pb2'
  # @@protoc_insertion_point(class_scope:HeroPvpFightCfg.CfgTable)
  })
_sym_db.RegisterMessage(CfgTable)

Cfg = _reflection.GeneratedProtocolMessageType('Cfg', (_message.Message,), {
  'DESCRIPTOR' : _CFG,
  '__module__' : 'HeroPvpFightCfg_pb2'
  # @@protoc_insertion_point(class_scope:HeroPvpFightCfg.Cfg)
  })
_sym_db.RegisterMessage(Cfg)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CFGTABLE._serialized_start=42
  _CFGTABLE._serialized_end=88
  _CFG._serialized_start=91
  _CFG._serialized_end=379
# @@protoc_insertion_point(module_scope)
