# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SummonerCfg.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11SummonerCfg.proto\x12\x0bSummonerCfg\"*\n\x08\x43\x66gTable\x12\x1e\n\x04\x44\x61ta\x18\x01 \x03(\x0b\x32\x10.SummonerCfg.Cfg\"\xa7\x02\n\x03\x43\x66g\x12\n\n\x02Id\x18\x01 \x01(\x05\x12\x0c\n\x04Name\x18\x02 \x01(\t\x12\x0c\n\x04Info\x18\x03 \x01(\t\x12\r\n\x05SrcId\x18\x04 \x01(\x05\x12\x11\n\tIntensity\x18\x05 \x01(\x05\x12\x0e\n\x06\x43\x61reer\x18\x06 \x01(\x05\x12\x0c\n\x04\x43\x61mp\x18\x07 \x01(\x05\x12\r\n\x05Range\x18\x08 \x01(\x05\x12\x0f\n\x07MoveSpd\x18\t \x01(\x05\x12\x12\n\nEnemySkill\x18\n \x03(\x05\x12\x12\n\nMonsterTag\x18\x0b \x03(\x05\x12\x16\n\x0eIsShowStateBar\x18\x0c \x01(\x08\x12\x15\n\rIsShowInfoBar\x18\r \x01(\x08\x12\x15\n\rContainAction\x18\x0e \x01(\x08\x12\x19\n\x11\x43ontainFacadeComp\x18\x0f \x01(\x08\x12\x0f\n\x07\x42reakId\x18\x10 \x01(\x05\x62\x06proto3')



_CFGTABLE = DESCRIPTOR.message_types_by_name['CfgTable']
_CFG = DESCRIPTOR.message_types_by_name['Cfg']
CfgTable = _reflection.GeneratedProtocolMessageType('CfgTable', (_message.Message,), {
  'DESCRIPTOR' : _CFGTABLE,
  '__module__' : 'SummonerCfg_pb2'
  # @@protoc_insertion_point(class_scope:SummonerCfg.CfgTable)
  })
_sym_db.RegisterMessage(CfgTable)

Cfg = _reflection.GeneratedProtocolMessageType('Cfg', (_message.Message,), {
  'DESCRIPTOR' : _CFG,
  '__module__' : 'SummonerCfg_pb2'
  # @@protoc_insertion_point(class_scope:SummonerCfg.Cfg)
  })
_sym_db.RegisterMessage(Cfg)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CFGTABLE._serialized_start=34
  _CFGTABLE._serialized_end=76
  _CFG._serialized_start=79
  _CFG._serialized_end=374
# @@protoc_insertion_point(module_scope)
